<?php
// Developed by Dennis Stevense for Digital Deployment

/**
 * Implementation of hook_cron().
 */
function date_trigger_cron() {
  // Iterate all date fields
  $fields = date_trigger_fields();
  foreach ($fields as $field) {
    $event_name = date_trigger_event_name($field);

    // Check if there are any rules for this event, so that we don't go query the database for nothing
    $set = rules_get_rule_set('event_' . $event_name);
    if (isset($set['rules']) && !empty($set['rules'])) {
      $database_info = content_database_info($field);
      if (!isset($database_info['table']) || !isset($database_info['columns']['value']['column'])) {
        continue;
      }
      $table = $database_info['table'];
      $column = $database_info['columns']['value']['column'];
      
      $field_name = $field['field_name'];
      $field_type = $field['type'];
      
      switch ($field_type) {
        case 'date':
          $date = date_format(date_now(), DATE_FORMAT_ISO);
          $date_placeholder = "'%s'";
          break;
          
        case 'datetime':
          $date = date_format(date_now(), DATE_FORMAT_DATETIME);
          $date_placeholder = "'%s'";
          break;
        
        case 'datestamp':
          $date = date_format(date_now(), DATE_FORMAT_UNIX);
          $date_placeholder = "%d";
          break;
        
        default:
          continue;
      }
      
      // Find all nodes whose date has passed
      $result = db_query("SELECT f.nid, f.$column AS value FROM {$table} f LEFT JOIN {date_trigger_invocation} i ON i.nid = f.nid AND i.field_name = '%s' AND i.{$field_type}_value = f.$column WHERE f.$column <= $date_placeholder AND i.{$field_type}_value IS NULL", $field_name, $date);
      while ($record = db_fetch_object($result)) {
        $node = node_load($record->nid);

        // Trigger the event
        rules_invoke_event($event_name, $node);

        // Make sure we don't trigger it again
        db_query("DELETE FROM {date_trigger_invocation} WHERE nid = %d AND field_name = '%s'", $record->nid, $field_name);
        db_query("INSERT INTO {date_trigger_invocation} (nid, field_name, {$field_type}_value) VALUES (%d, '%s', $date_placeholder)", $record->nid, $field_name, $record->value);
      }
    }
  }
}

/**
 * Implementation of hook_rules_event_info().
 */
function date_trigger_rules_event_info() {
  $events = array();
  
  // Iterate all date fields
  $fields = date_trigger_fields();
  foreach ($fields as $field) {
    $event_name = date_trigger_event_name($field);
    
    // Find an appropriate human-readable name for the field
    if (isset($field['widget']['label'])) {
      $field_label = $field['widget']['label'];
    }
    else {
      $field_label = $field['field_name'];
    }
    
    $events[$event_name] = array(
      'label' => t('Once after \'@field_label\' has passed', array('@field_label' => $field_label)),
      'module' => 'Date trigger',
      'arguments' => array(
        'node' => array(
          'type' => 'node', 
          'label' => t('content on which date has passed'),
        ),
      ),
    );
  }
  
  return $events;
}

/**
 * Returns the rules event name for the given field.
 */
function date_trigger_event_name($field) {
  return 'date_trigger_' . $field['field_name'];
}

/**
 * Returns the fields that this module supports.
 */
function date_trigger_fields() {
  static $fields;
  
  // Establish the array if we don't have cached statically
  if (!isset($fields)) {
    $fields = array();
    
    // Iterate all fields
    $all_fields = content_fields();
    foreach ($all_fields as $field) {
      // We need to check this, according to the content_fields() documentation
      if (!isset($field['field_name']) || empty($field['field_name'])) {
        continue;
      }

      // Check if this is a date field
      if (in_array($field['type'], array('date', 'datestamp', 'datetime'))) {
        $fields[] = $field;
      }
    }
  }

  return $fields;
}
